#!/bin/sh

j=`date +"%j"`
x=`expr $j % 7 `
if [ $# -ge 1 ] ; then
  export arg=$1
else
  export arg="N"
fi

cd $HOME/noscrub/verification/
if [ $x -eq 0 -o $arg == "f" ] ; then
  wget -nv --mirror ftp://osisaf.met.no/archive/ice/conc/2023/
  wget -nv --mirror ftp://osisaf.met.no/archive/ice/conc/2020/02
  wget -nv --mirror ftp://osisaf.met.no/archive/ice/conc/2020/0[3-9]
fi
