#!/bin/sh

#use .netrc 

echo cd gfs > l
#echo put alert* >> l
echo put ncep_gfs_sflux.20180201.tgz >> l
echo quit >> l
cat l | ftp ftp.ecmwf.int

#echo put alert* > l
echo put ncep_gfs_sflux.20180201.tgz >> l
echo quit >> l
cat l | ftp ftp1.psl.noaa.gov

rm l
#rm *.tgz
