#!/bin/sh

if [ $# -ne 1 ] ; then
  echo need exactly 1 argument -- 8 digit date of files
  exit 1
fi
tag=$1

echo cd gfs > l
echo put ncep_gfs_sflux.${tag}.tgz >> l
echo put ncep_gfs_pgrb.${tag}.tgz >> l
echo quit >> l
cat l | ftp ftp.ecmwf.int

echo put ncep_gfs_sflux.${tag}.tgz >> l
echo put ncep_gfs_pgrb.${tag}.tgz >> l
echo quit >> l
cat l | ftp ftp1.psl.noaa.gov

rm l
