#!/bin/sh

# Setting up an environment to run in, but 'environment' is a special 
#   word in use, as is 'home'
# Robert Grumbine 13 Feb 2024

# Wcoss2:
source $HOME/env3.10/bin/activate
module load PrgEnv-intel netcdf

# Hera:
#source $HOME/env3.7/bin/activate
#module load hpc/1.2.0  hpc-intel/2022.1.2
#module load netcdf/4.9.0


# All:
export PYTHONPATH=$PYTHONPATH:$HOME/rgdev/toolbox/amsr2.filter/gists:$HOME/rgdev/toolbox/amsr2.filter/shared:$HOME/rgops/mmablib/py

